// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rocinehvitcqfstcwntt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvY2luZWh2aXRjcWZzdGN3bnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mjk4ODUsImV4cCI6MjA3MDQwNTg4NX0.mA5kgJ7AqKGsuu3xNZKfnB2mivF6W-JaXDlv5Ncg3yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});